name: vidio
description: Vidio is a lightweight and customizable video player library for Flutter. It provides seamless video playback with flexible APIs to build your own controls, overlays, and advanced features. Vidio is designed for performance, ease of integration, and full extensibility to suit any Flutter appâ€™s video playback requirements.
version: 1.0.0

environment:
  sdk: ^3.2.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.4
  video_player: ^2.8.1
  wakelock_plus: ^1.1.6
  audio_video_progress_bar: ^2.0.3
  path: ^1.8.3
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1

dependency_overrides:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/

